# Generated by Django 2.2.5 on 2019-09-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('title', models.CharField(max_length=256)),
                ('pub_time', models.DateTimeField(null=True)),
                ('source', models.CharField(max_length=64, null=True)),
                ('content', models.TextField()),
                ('text', models.TextField(default='', null=True)),
                ('newsID', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('word', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
