# Generated by Django 2.2.5 on 2019-09-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordmodel',
            name='related_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.TeamModel'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='contain_words',
            field=models.ManyToManyField(through='search.FreqModel', to='search.WordModel'),
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='related_teams',
            field=models.ManyToManyField(through='team.RelationModel', to='team.TeamModel'),
        ),
        migrations.AddField(
            model_name='freqmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.NewsModel'),
        ),
        migrations.AddField(
            model_name='freqmodel',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.WordModel'),
        ),
    ]
