# Generated by Django 2.2.5 on 2019-09-06 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('abbr', models.CharField(max_length=8)),
                ('division', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('teamID', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RelationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.FloatField(default=0)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.NewsModel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.TeamModel')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('code', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=16)),
                ('country', models.CharField(max_length=64)),
                ('playerID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('weight', models.CharField(max_length=32)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.TeamModel')),
            ],
        ),
    ]
